### ISSUE TITLE
Wrong dates in calendar.

### ISSUE THREAD

**Issue by TupiniViking** [Ordisoftware/Hebrew-Calendar#1221] opened 2022-10-27 17:10 UTC
I'm learning about Torah now and so I'm new to the subject.
I installed the Hebrew Calendar software but something is not correct.
Today the 27th of October in the year 2022 is supposed to be the 2nd of the month of Cheshvan in the year 5783.
This week's study Parasha runs from Genesis / Bereshit chapter 6 verse 9 to chapter 11 verse 32.
There is also further study of Numbers chapter 28 verses 1 through verse 15.
There is also additional study of Isaiah/Yeshuayahu Chapter 54 verses 1 through 10.

The software is informing us that the 5th of October we must separate the lamb and that from the 9th to the 15th it was Pessa'h.

Only we just had Yom Kippur and the feast of Sukot.

Was it something in the installation that caused this divergence?

How can I do to fix it?

My source for information about dates is the website:

https://www.chabad.org/

**Comment by Ordisoftware** [comment] 2022-10-27 17:29
Duplicate of https://github.com/Ordisoftware/Hebrew-Calendar/issues/1208

[What are the times of celebration?](https://github.com/Ordisoftware/Hebrew-Calendar#what-are-the-times-of-celebration)

**Closed by Ordisoftware** 2022-10-27 17:29 UTC
